# atcli shell integration -- generated by `atcli init zsh`
#
# atcli 本体は cwd を親 shell に反映できないため、`atcli new --cd` と `atcli cd` は
# ここで出力されたパスを受け取って `builtin cd` する。
atcli() {
  emulate -L zsh
  local _atcli_dir _atcli_arg _atcli_cd=0

  case "$1" in
    cd)
      shift
      _atcli_dir="$(ATCLI_SHELL_INTEGRATION=1 command atcli cd "$@")" || return
      builtin cd "$_atcli_dir"
      return
      ;;
    new)
      for _atcli_arg in "$@"; do
        [[ "$_atcli_arg" == "--cd" ]] && _atcli_cd=1
      done
      if (( _atcli_cd )); then
        _atcli_dir="$(ATCLI_SHELL_INTEGRATION=1 command atcli "$@")" || return
        builtin cd "$_atcli_dir"
        return
      fi
      ;;
  esac

  command atcli "$@"
}

atcd() { atcli cd "$@"; }
